export const GERMAN_VIDEO_PROMPTS = [
  'Eine futuristische Stadt bei Nacht mit fliegenden Autos und Neonlichtern.',
  'Ein majestätischer Löwe, der durch die Savanne streift, während die Sonne untergeht.',
  'Ein Astronaut, der auf einer fremden Welt mit lila Pflanzen landet.',
  'Ein gemütliches Café in Paris im Regen, gesehen durch ein Fenster mit Regentropfen.',
  'Eine Zeitrafferaufnahme einer blühenden Rose in einem verzauberten Garten.',
  'Ein Cyberpunk-Straßenmarkt in Tokio mit Robotern und geschäftigem Treiben.',
  'Eine Unterwasserwelt mit bunten Korallenriffen und exotischen Fischen.',
  'Ein alter Zauberer, der in einer Bibliothek voller schwebender Bücher Zaubersprüche wirkt.',
  'Eine Drohnenaufnahme über schneebedeckte Alpengipfel bei Sonnenaufgang.',
  'Ein Welpe, der zum ersten Mal im Herbstlaub spielt.',
  'Eine epische Schlacht zwischen Drachen und Rittern in einer Fantasy-Landschaft.',
  'Ein friedlicher Zen-Garten mit fließendem Wasser und fallenden Kirschblüten.',
  'Eine Steampunk-Dampflokomotive, die durch eine viktorianische Stadt fährt.',
  'Ein surrealer Traum mit schmelzenden Uhren und schwebenden Inseln.',
  'Eine Gruppe von Freunden, die am Lagerfeuer am Strand Gitarre spielen.',
  'Ein Formel-1-Rennen mit hoher Geschwindigkeit und verschwommenen Hintergründen.',
  'Eine mikroskopische Ansicht von Zellen, die sich teilen und interagieren.',
  'Ein einsamer Leuchtturm inmitten eines stürmischen Ozeans mit hohen Wellen.',
  'Eine geschäftige Küche in einem Sternerestaurant, in der Köche Gerichte zubereiten.',
  'Ein Astronaut, der im Weltraum schwebt und auf die blaue Erde hinunterblickt.',
];
